language: python

matrix:
  include:
    - python: '3.6'
    - python: '3.7'
    - os: osx
      osx_image: xcode11
      language: shell
    - python: '3.7'
      env:
        JS_TEST: 1

before_install:
  - python3 -m pip install -r requirements-dev.txt
  - python3 -m pip freeze

install:
  - pip install . --no-deps
  - jlpm

before_script:
  - jlpm lint:check

script:
  - '[[ -z "$JS_TEST" ]] || jlpm test'
  - '[[ -z "$JS_TEST" ]] && python3 -m setup.py test'

addons:
  apt:
    packages:
      - nodejs
