language: python

python:
  - "3.6"

before_install:
  - pip install -r requirements.txt
  - pip freeze

install:
  - pip install . --no-deps
  - jlpm

before_script:
  - jlpm lint:check

script:
  - jlpm test

addons:
  apt:
    sources:
      - sourceline: ppa:deadsnakes/ppa
    packages:
      - nodejs
