language: node_js
dist: xenial
node_js:
  - '11'
before_install:
  - pip3 install --user -r requirements.txt
  - pip3 freeze
install:
  - pip3 install --user -e .
  - jlpm
before_script:
  - jlpm lint:check
script:
  - jlpm test
