language: node_js
node_js:
  - '11'
before_install:
  - pip install --user -r requirements.txt
  - pip freeze
install:
  - pip install --user -e .
  - jlpm
before_script:
  - jlpm lint:check
script:
  - jlpm test
