language: python

cache:
  directories:
    - .yarn-packages
    - $HOME/.cache/pip

matrix:
  include:
    - python: '3.6'
    - python: '3.7'
    - os: osx
      osx_image: xcode11
      language: shell

before_install:
  - python3 -m pip install -r requirements-dev.txt
  - python3 -m pip freeze

install:
  - pip install . --no-deps
  - jlpm

script:
  - python3 -m setup.py test
  - jlpm test

addons:
  apt:
    packages:
      - nodejs
