name: jupyterlab-lsp

channels:
  - conda-forge
  - defaults
  - r

dependencies:
  - black
  - flake8 >=3.5
  - isort
  - jupyterlab >=1.1,<1.2
  - mypy
  - nodejs
  - pip
  - pylint
  - python >=3.7,<3.8.0a0
  - python-language-server
  # for R:
  - libcurl
  - r-base
  - r-remotes
  - r-curl
  - r-languageserver
  - pip:
      - pyls-black
      - pyls-isort
      - pyls-mypy
