name: jupyterlab-lsp-docs

channels:
  - conda-forge

dependences:
  - nbsphinx
  - pandas
  - python-graphviz
  - recommonmark
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
