name: jupyterlab-lsp

channels:
  - conda-forge
  - nodefaults

dependencies:
  # runtime dependencies
  - python >=3.6,<3.9.0a0
  - jupyterlab >=3.0.0,<4.0.0a0
  - notebook >=4.3.1
  # build dependencies
  - nodejs >=10.12,<15
  # for python language server (and development)
  - flake8 >=3.5
  - pip
  - pylint
  - pyls-black
  - pyls-isort
  - pyls-mypy
  - python-language-server
  - ruamel_yaml
  # for R language server and kernel
  - r
  - r-irkernel
  - r-languageserver
  - rpy2
  # for tex
  - tectonic
  - texlab
  - chktex
  # TODO: remove when jedi vs IPython is resolved
  - jedi <0.18
