name: jupyterlab-lsp

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - isort
  - jupyter-server-proxy
  - jupyterlab >=1.1,<1.2
  - mypy
  - nodejs
  - pip
  - python >=3.7,<3.8.0a0
  - python-language-server
  - pip:
      - pyls-black
      - pyls-isort
      - pyls-mypy
