name: lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
        python: [3.8]
        nodejs: ['>=12,<13.0.0a0']
        lab: ['>=3.0.0,<4.0.0a0']
    steps:
      - uses: actions/checkout@v2

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{'
          tokenSuffix: '}'
          files: '["requirements/github-actions.yml"]'
        env:
          lab: '${{ matrix.lab }}'
          nodejs: '${{ matrix.nodejs }}'

      - name: Set up Python and conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          channel-priority: true
          activate-environment: jupyterlab-lsp
          environment-file: requirements/github-actions.yml
          auto-update-conda: true

      - name: linting dependencies
        run: conda env update -n jupyterlab-lsp --file requirements/lint.yml --quiet

      - name: check integrity of package versions
        run: python scripts/integrity.py

      - name: install npm dependencies
        run: jlpm

      - name: lint backend
        run: python scripts/lint.py

      - name: build schema so linting can complete
        run: jlpm build:schema

      - name: lint frontend
        run: jlpm lint:check
