name: Run acceptance tests
on: [push, pull_request]

strategy:
  matrix:
    os: [ubuntu-16.04]
    python: [3.8]
    nodejs: ['>=12,<13.0.0a0']
    lap: '>=2,<3.0.0a0'

env:
  PY_JLSP_VERSION: 0.9.2
  JS_JLLSP_VERSION: 2.0.2
  JS_JLG2D_VERSION: 1.0.0

jobs:
  - Lint:
    runs-on: ${{ matrix.os }}
    defaults:
      shell: bash -l {0}
    steps:
      - name: Set up Python and conda
        uses: goanpeca/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python }}
          conda-channels: conda-forge, anaconda
          channel-priority: true
          mamba-version: "*"
          auto-activate-base: true
          auto-update-conda: false

      - name: generate env with lab and node version
        run: cd .github/workflows && python env_template.py "${{ matrix.lab }}" "{{ matrix.nodejs }}"

      - name: testing dependencies
        run: conda env update -n jupyterlab-lsp --file env-test.yml --quiet

      - name: linting dependencies
        run: conda env update -n jupyterlab-lsp --file requirements/lint.yml --quiet

      - name: check integrity of package versions
        run: jupyterlab-lsp && python scripts/integrity.py

      - name: install npm dependencies
        run: jupyterlab-lsp && jlpm || jlpm || jlpm

      - name: lint backend
        run: jupyterlab-lsp && python scripts/lint.py

      - name: build schema so linting can complete
        run: jupyterlab-lsp && jlpm build:schema

      - name: lint frontend
        run: jupyterlab-lsp && jlpm lint:check
